### ISSUE TITLE
Create collection API and add pagination to collection manager

### ISSUE THREAD

**Issue by AlanOC91** [AlanOC91/YGOPRODeck#254]
This is a needed change to improve performance of large user collections.

Currently some users have 5k+ cards in their collection. This causes the collection view to become slow and potentially buggy, showcasing incorrect information.

Adding pagination along with other dedicated collection filters will improve this vastly.

**Comment by AlanOC91** [comment]
Collection API + Pagination is completed and now in testing phase.
Performance for large collections has now significantly improved when viewing collection.

**Comment by AlanOC91** [comment]
Currently added:

- Collection Ajax Paging
- Paging only appears if there are more than 500 unique rows (not 500 cards)
- Size of Current Page + Total Collection Size
- Collection Dynamic Caching. Collection Content is cached and cache is automatically deleted when cards are updated/removed/added to the collection. This will improve performance for users who are browsing large collections

**Comment by AlanOC91** [comment]
This is now live and the new collection manager is available for everyone.

- Fixed a bug where you couldn't search by name within the collection.
- Added "Quantity" to the sort dropdown.

**Comment by michaelolson1996** [comment]
Hi Alan, first of all thank you for the work you have done, the api is fantastic. I wanted to reach out via the website but was unable to leave a message. I am interested in setting up a monthly pull from the database, where I pull all cards and compare it to the cards on my local system, as opposed to sending constant queries when a user needs them. it appears that I can do this with the base url, and just wanted to make sure that there are no issues with this approach. Thanks again!

**Comment by AlanOC91** [comment]
> Hi Alan, first of all thank you for the work you have done, the api is fantastic. I wanted to reach out via the website but was unable to leave a message. I am interested in setting up a monthly pull from the database, where I pull all cards and compare it to the cards on my local system, as opposed to sending constant queries when a user needs them. it appears that I can do this with the base url, and just wanted to make sure that there are no issues with this approach. Thanks again!

Hi Michael, that's no problem at all. Thanks! :)

**Comment by iNarute** [comment]
Heya, it seems that the website still misses out some cards, not sure why. I don't have a large amount of cards, but I did at one point have around 5k so it was possible from passing that amount, though with the new update it still happens strangely enough, or it started happening at a specific point, though I'm not sure why it would happen. I appreciate the work you put in though, not many people would do this much, and for free as well!

**Comment by SovietSIav** [comment]
Update: I noticed that even if your cards disappear in the main collection, they're still all there if you open the deck builder

**Comment by AlanOC91** [comment]
New Issue which should fix these issues: #265
